packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/**'
  # exclude packages that are inside test directories
  - '!**/test/**'

savePrefix: ''
catalog:
  '@antfu/eslint-config': ^8.0.0
  del-cli: 7.0.0
  eslint: ^10.0.0
  eslint-plugin-format: ^2.0.0
  lint-staged: ^16.2.7
  prettier: ^3.7.3
  simple-git-hooks: ^2.13.1
  typescript: 5.9.3
  vitest: 4.1.5
  zshy: 0.7.0
