packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/**'
  # exclude packages that are inside test directories
  - '!**/test/**'

savePrefix: ''
catalog:
  '@antfu/eslint-config': ^6.2.0
  del-cli: 6.0.0
  eslint: ^9.38.0
  eslint-plugin-format: ^1.0.2
  lint-staged: ^16.2.7
  prettier: ^3.7.3
  simple-git-hooks: ^2.13.1
  typescript: 5.9.3
  vitest: 4.0.14
  zshy: 0.6.0
